// Code generated by mockery v2.53.2. DO NOT EDIT.

package srvc

import (
	context "context"

	srvc "github.com/programme-lv/backend/task/srvc"
	mock "github.com/stretchr/testify/mock"
)

// MockTaskPgRepo is an autogenerated mock type for the TaskPgRepo type
type MockTaskPgRepo struct {
	mock.Mock
}

type MockTaskPgRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskPgRepo) EXPECT() *MockTaskPgRepo_Expecter {
	return &MockTaskPgRepo_Expecter{mock: &_m.Mock}
}

// AddStatementImg provides a mock function with given fields: ctx, taskId, img
func (_m *MockTaskPgRepo) AddStatementImg(ctx context.Context, taskId string, img srvc.StatementImage) error {
	ret := _m.Called(ctx, taskId, img)

	if len(ret) == 0 {
		panic("no return value specified for AddStatementImg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, srvc.StatementImage) error); ok {
		r0 = rf(ctx, taskId, img)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskPgRepo_AddStatementImg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddStatementImg'
type MockTaskPgRepo_AddStatementImg_Call struct {
	*mock.Call
}

// AddStatementImg is a helper method to define mock.On call
//   - ctx context.Context
//   - taskId string
//   - img srvc.StatementImage
func (_e *MockTaskPgRepo_Expecter) AddStatementImg(ctx interface{}, taskId interface{}, img interface{}) *MockTaskPgRepo_AddStatementImg_Call {
	return &MockTaskPgRepo_AddStatementImg_Call{Call: _e.mock.On("AddStatementImg", ctx, taskId, img)}
}

func (_c *MockTaskPgRepo_AddStatementImg_Call) Run(run func(ctx context.Context, taskId string, img srvc.StatementImage)) *MockTaskPgRepo_AddStatementImg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(srvc.StatementImage))
	})
	return _c
}

func (_c *MockTaskPgRepo_AddStatementImg_Call) Return(_a0 error) *MockTaskPgRepo_AddStatementImg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskPgRepo_AddStatementImg_Call) RunAndReturn(run func(context.Context, string, srvc.StatementImage) error) *MockTaskPgRepo_AddStatementImg_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTask provides a mock function with given fields: ctx, task
func (_m *MockTaskPgRepo) CreateTask(ctx context.Context, task srvc.Task) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, srvc.Task) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskPgRepo_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockTaskPgRepo_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task srvc.Task
func (_e *MockTaskPgRepo_Expecter) CreateTask(ctx interface{}, task interface{}) *MockTaskPgRepo_CreateTask_Call {
	return &MockTaskPgRepo_CreateTask_Call{Call: _e.mock.On("CreateTask", ctx, task)}
}

func (_c *MockTaskPgRepo_CreateTask_Call) Run(run func(ctx context.Context, task srvc.Task)) *MockTaskPgRepo_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(srvc.Task))
	})
	return _c
}

func (_c *MockTaskPgRepo_CreateTask_Call) Return(_a0 error) *MockTaskPgRepo_CreateTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskPgRepo_CreateTask_Call) RunAndReturn(run func(context.Context, srvc.Task) error) *MockTaskPgRepo_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteStatementImg provides a mock function with given fields: ctx, taskId, filename
func (_m *MockTaskPgRepo) DeleteStatementImg(ctx context.Context, taskId string, filename string) error {
	ret := _m.Called(ctx, taskId, filename)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStatementImg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, taskId, filename)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskPgRepo_DeleteStatementImg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStatementImg'
type MockTaskPgRepo_DeleteStatementImg_Call struct {
	*mock.Call
}

// DeleteStatementImg is a helper method to define mock.On call
//   - ctx context.Context
//   - taskId string
//   - filename string
func (_e *MockTaskPgRepo_Expecter) DeleteStatementImg(ctx interface{}, taskId interface{}, filename interface{}) *MockTaskPgRepo_DeleteStatementImg_Call {
	return &MockTaskPgRepo_DeleteStatementImg_Call{Call: _e.mock.On("DeleteStatementImg", ctx, taskId, filename)}
}

func (_c *MockTaskPgRepo_DeleteStatementImg_Call) Run(run func(ctx context.Context, taskId string, filename string)) *MockTaskPgRepo_DeleteStatementImg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTaskPgRepo_DeleteStatementImg_Call) Return(_a0 error) *MockTaskPgRepo_DeleteStatementImg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskPgRepo_DeleteStatementImg_Call) RunAndReturn(run func(context.Context, string, string) error) *MockTaskPgRepo_DeleteStatementImg_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, shortId
func (_m *MockTaskPgRepo) Exists(ctx context.Context, shortId string) (bool, error) {
	ret := _m.Called(ctx, shortId)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, shortId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, shortId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskPgRepo_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockTaskPgRepo_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - shortId string
func (_e *MockTaskPgRepo_Expecter) Exists(ctx interface{}, shortId interface{}) *MockTaskPgRepo_Exists_Call {
	return &MockTaskPgRepo_Exists_Call{Call: _e.mock.On("Exists", ctx, shortId)}
}

func (_c *MockTaskPgRepo_Exists_Call) Run(run func(ctx context.Context, shortId string)) *MockTaskPgRepo_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskPgRepo_Exists_Call) Return(_a0 bool, _a1 error) *MockTaskPgRepo_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskPgRepo_Exists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockTaskPgRepo_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// GetTask provides a mock function with given fields: ctx, shortId
func (_m *MockTaskPgRepo) GetTask(ctx context.Context, shortId string) (srvc.Task, error) {
	ret := _m.Called(ctx, shortId)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 srvc.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (srvc.Task, error)); ok {
		return rf(ctx, shortId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) srvc.Task); ok {
		r0 = rf(ctx, shortId)
	} else {
		r0 = ret.Get(0).(srvc.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskPgRepo_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type MockTaskPgRepo_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - ctx context.Context
//   - shortId string
func (_e *MockTaskPgRepo_Expecter) GetTask(ctx interface{}, shortId interface{}) *MockTaskPgRepo_GetTask_Call {
	return &MockTaskPgRepo_GetTask_Call{Call: _e.mock.On("GetTask", ctx, shortId)}
}

func (_c *MockTaskPgRepo_GetTask_Call) Run(run func(ctx context.Context, shortId string)) *MockTaskPgRepo_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskPgRepo_GetTask_Call) Return(_a0 srvc.Task, _a1 error) *MockTaskPgRepo_GetTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskPgRepo_GetTask_Call) RunAndReturn(run func(context.Context, string) (srvc.Task, error)) *MockTaskPgRepo_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskPreview provides a mock function with given fields: ctx, shortId
func (_m *MockTaskPgRepo) GetTaskPreview(ctx context.Context, shortId string) (srvc.TaskPreview, error) {
	ret := _m.Called(ctx, shortId)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskPreview")
	}

	var r0 srvc.TaskPreview
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (srvc.TaskPreview, error)); ok {
		return rf(ctx, shortId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) srvc.TaskPreview); ok {
		r0 = rf(ctx, shortId)
	} else {
		r0 = ret.Get(0).(srvc.TaskPreview)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskPgRepo_GetTaskPreview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskPreview'
type MockTaskPgRepo_GetTaskPreview_Call struct {
	*mock.Call
}

// GetTaskPreview is a helper method to define mock.On call
//   - ctx context.Context
//   - shortId string
func (_e *MockTaskPgRepo_Expecter) GetTaskPreview(ctx interface{}, shortId interface{}) *MockTaskPgRepo_GetTaskPreview_Call {
	return &MockTaskPgRepo_GetTaskPreview_Call{Call: _e.mock.On("GetTaskPreview", ctx, shortId)}
}

func (_c *MockTaskPgRepo_GetTaskPreview_Call) Run(run func(ctx context.Context, shortId string)) *MockTaskPgRepo_GetTaskPreview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskPgRepo_GetTaskPreview_Call) Return(_a0 srvc.TaskPreview, _a1 error) *MockTaskPgRepo_GetTaskPreview_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskPgRepo_GetTaskPreview_Call) RunAndReturn(run func(context.Context, string) (srvc.TaskPreview, error)) *MockTaskPgRepo_GetTaskPreview_Call {
	_c.Call.Return(run)
	return _c
}

// ListTaskPreviews provides a mock function with given fields: ctx, limit, offset
func (_m *MockTaskPgRepo) ListTaskPreviews(ctx context.Context, limit int, offset int) ([]srvc.TaskPreview, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListTaskPreviews")
	}

	var r0 []srvc.TaskPreview
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]srvc.TaskPreview, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []srvc.TaskPreview); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]srvc.TaskPreview)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskPgRepo_ListTaskPreviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTaskPreviews'
type MockTaskPgRepo_ListTaskPreviews_Call struct {
	*mock.Call
}

// ListTaskPreviews is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockTaskPgRepo_Expecter) ListTaskPreviews(ctx interface{}, limit interface{}, offset interface{}) *MockTaskPgRepo_ListTaskPreviews_Call {
	return &MockTaskPgRepo_ListTaskPreviews_Call{Call: _e.mock.On("ListTaskPreviews", ctx, limit, offset)}
}

func (_c *MockTaskPgRepo_ListTaskPreviews_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockTaskPgRepo_ListTaskPreviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockTaskPgRepo_ListTaskPreviews_Call) Return(_a0 []srvc.TaskPreview, _a1 error) *MockTaskPgRepo_ListTaskPreviews_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskPgRepo_ListTaskPreviews_Call) RunAndReturn(run func(context.Context, int, int) ([]srvc.TaskPreview, error)) *MockTaskPgRepo_ListTaskPreviews_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasks provides a mock function with given fields: ctx, limit, offset
func (_m *MockTaskPgRepo) ListTasks(ctx context.Context, limit int, offset int) ([]srvc.Task, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 []srvc.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]srvc.Task, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []srvc.Task); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]srvc.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskPgRepo_ListTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasks'
type MockTaskPgRepo_ListTasks_Call struct {
	*mock.Call
}

// ListTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockTaskPgRepo_Expecter) ListTasks(ctx interface{}, limit interface{}, offset interface{}) *MockTaskPgRepo_ListTasks_Call {
	return &MockTaskPgRepo_ListTasks_Call{Call: _e.mock.On("ListTasks", ctx, limit, offset)}
}

func (_c *MockTaskPgRepo_ListTasks_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockTaskPgRepo_ListTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockTaskPgRepo_ListTasks_Call) Return(_a0 []srvc.Task, _a1 error) *MockTaskPgRepo_ListTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskPgRepo_ListTasks_Call) RunAndReturn(run func(context.Context, int, int) ([]srvc.Task, error)) *MockTaskPgRepo_ListTasks_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveNames provides a mock function with given fields: ctx, shortIds
func (_m *MockTaskPgRepo) ResolveNames(ctx context.Context, shortIds []string) ([]string, error) {
	ret := _m.Called(ctx, shortIds)

	if len(ret) == 0 {
		panic("no return value specified for ResolveNames")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]string, error)); ok {
		return rf(ctx, shortIds)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []string); ok {
		r0 = rf(ctx, shortIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, shortIds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskPgRepo_ResolveNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveNames'
type MockTaskPgRepo_ResolveNames_Call struct {
	*mock.Call
}

// ResolveNames is a helper method to define mock.On call
//   - ctx context.Context
//   - shortIds []string
func (_e *MockTaskPgRepo_Expecter) ResolveNames(ctx interface{}, shortIds interface{}) *MockTaskPgRepo_ResolveNames_Call {
	return &MockTaskPgRepo_ResolveNames_Call{Call: _e.mock.On("ResolveNames", ctx, shortIds)}
}

func (_c *MockTaskPgRepo_ResolveNames_Call) Run(run func(ctx context.Context, shortIds []string)) *MockTaskPgRepo_ResolveNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockTaskPgRepo_ResolveNames_Call) Return(_a0 []string, _a1 error) *MockTaskPgRepo_ResolveNames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskPgRepo_ResolveNames_Call) RunAndReturn(run func(context.Context, []string) ([]string, error)) *MockTaskPgRepo_ResolveNames_Call {
	_c.Call.Return(run)
	return _c
}

// SearchTasksByName provides a mock function with given fields: ctx, name
func (_m *MockTaskPgRepo) SearchTasksByName(ctx context.Context, name string) ([]string, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for SearchTasksByName")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskPgRepo_SearchTasksByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchTasksByName'
type MockTaskPgRepo_SearchTasksByName_Call struct {
	*mock.Call
}

// SearchTasksByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTaskPgRepo_Expecter) SearchTasksByName(ctx interface{}, name interface{}) *MockTaskPgRepo_SearchTasksByName_Call {
	return &MockTaskPgRepo_SearchTasksByName_Call{Call: _e.mock.On("SearchTasksByName", ctx, name)}
}

func (_c *MockTaskPgRepo_SearchTasksByName_Call) Run(run func(ctx context.Context, name string)) *MockTaskPgRepo_SearchTasksByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskPgRepo_SearchTasksByName_Call) Return(_a0 []string, _a1 error) *MockTaskPgRepo_SearchTasksByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskPgRepo_SearchTasksByName_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *MockTaskPgRepo_SearchTasksByName_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIllustrationImg provides a mock function with given fields: ctx, taskId, img
func (_m *MockTaskPgRepo) UpdateIllustrationImg(ctx context.Context, taskId string, img srvc.IllustrationImage) error {
	ret := _m.Called(ctx, taskId, img)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIllustrationImg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, srvc.IllustrationImage) error); ok {
		r0 = rf(ctx, taskId, img)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskPgRepo_UpdateIllustrationImg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIllustrationImg'
type MockTaskPgRepo_UpdateIllustrationImg_Call struct {
	*mock.Call
}

// UpdateIllustrationImg is a helper method to define mock.On call
//   - ctx context.Context
//   - taskId string
//   - img srvc.IllustrationImage
func (_e *MockTaskPgRepo_Expecter) UpdateIllustrationImg(ctx interface{}, taskId interface{}, img interface{}) *MockTaskPgRepo_UpdateIllustrationImg_Call {
	return &MockTaskPgRepo_UpdateIllustrationImg_Call{Call: _e.mock.On("UpdateIllustrationImg", ctx, taskId, img)}
}

func (_c *MockTaskPgRepo_UpdateIllustrationImg_Call) Run(run func(ctx context.Context, taskId string, img srvc.IllustrationImage)) *MockTaskPgRepo_UpdateIllustrationImg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(srvc.IllustrationImage))
	})
	return _c
}

func (_c *MockTaskPgRepo_UpdateIllustrationImg_Call) Return(_a0 error) *MockTaskPgRepo_UpdateIllustrationImg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskPgRepo_UpdateIllustrationImg_Call) RunAndReturn(run func(context.Context, string, srvc.IllustrationImage) error) *MockTaskPgRepo_UpdateIllustrationImg_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatement provides a mock function with given fields: ctx, taskId, statement
func (_m *MockTaskPgRepo) UpdateStatement(ctx context.Context, taskId string, statement srvc.MarkdownStatement) error {
	ret := _m.Called(ctx, taskId, statement)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatement")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, srvc.MarkdownStatement) error); ok {
		r0 = rf(ctx, taskId, statement)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskPgRepo_UpdateStatement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatement'
type MockTaskPgRepo_UpdateStatement_Call struct {
	*mock.Call
}

// UpdateStatement is a helper method to define mock.On call
//   - ctx context.Context
//   - taskId string
//   - statement srvc.MarkdownStatement
func (_e *MockTaskPgRepo_Expecter) UpdateStatement(ctx interface{}, taskId interface{}, statement interface{}) *MockTaskPgRepo_UpdateStatement_Call {
	return &MockTaskPgRepo_UpdateStatement_Call{Call: _e.mock.On("UpdateStatement", ctx, taskId, statement)}
}

func (_c *MockTaskPgRepo_UpdateStatement_Call) Run(run func(ctx context.Context, taskId string, statement srvc.MarkdownStatement)) *MockTaskPgRepo_UpdateStatement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(srvc.MarkdownStatement))
	})
	return _c
}

func (_c *MockTaskPgRepo_UpdateStatement_Call) Return(_a0 error) *MockTaskPgRepo_UpdateStatement_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskPgRepo_UpdateStatement_Call) RunAndReturn(run func(context.Context, string, srvc.MarkdownStatement) error) *MockTaskPgRepo_UpdateStatement_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskPgRepo creates a new instance of MockTaskPgRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskPgRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskPgRepo {
	mock := &MockTaskPgRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
