// Code generated by mockery v2.53.2. DO NOT EDIT.

package mockuser

import (
	context "context"

	user "github.com/programme-lv/backend/user"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUserSrvcClient is an autogenerated mock type for the UserSrvcClient type
type MockUserSrvcClient struct {
	mock.Mock
}

type MockUserSrvcClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserSrvcClient) EXPECT() *MockUserSrvcClient_Expecter {
	return &MockUserSrvcClient_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, _a1
func (_m *MockUserSrvcClient) CreateUser(ctx context.Context, _a1 user.CreateUserParams) (*user.User, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, user.CreateUserParams) (*user.User, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user.CreateUserParams) *user.User); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, user.CreateUserParams) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserSrvcClient_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserSrvcClient_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 user.CreateUserParams
func (_e *MockUserSrvcClient_Expecter) CreateUser(ctx interface{}, _a1 interface{}) *MockUserSrvcClient_CreateUser_Call {
	return &MockUserSrvcClient_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, _a1)}
}

func (_c *MockUserSrvcClient_CreateUser_Call) Run(run func(ctx context.Context, _a1 user.CreateUserParams)) *MockUserSrvcClient_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(user.CreateUserParams))
	})
	return _c
}

func (_c *MockUserSrvcClient_CreateUser_Call) Return(_a0 *user.User, _a1 error) *MockUserSrvcClient_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserSrvcClient_CreateUser_Call) RunAndReturn(run func(context.Context, user.CreateUserParams) (*user.User, error)) *MockUserSrvcClient_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUUID provides a mock function with given fields: ctx, _a1
func (_m *MockUserSrvcClient) GetUserByUUID(ctx context.Context, _a1 uuid.UUID) (user.User, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUUID")
	}

	var r0 user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (user.User, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) user.User); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserSrvcClient_GetUserByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUUID'
type MockUserSrvcClient_GetUserByUUID_Call struct {
	*mock.Call
}

// GetUserByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 uuid.UUID
func (_e *MockUserSrvcClient_Expecter) GetUserByUUID(ctx interface{}, _a1 interface{}) *MockUserSrvcClient_GetUserByUUID_Call {
	return &MockUserSrvcClient_GetUserByUUID_Call{Call: _e.mock.On("GetUserByUUID", ctx, _a1)}
}

func (_c *MockUserSrvcClient_GetUserByUUID_Call) Run(run func(ctx context.Context, _a1 uuid.UUID)) *MockUserSrvcClient_GetUserByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserSrvcClient_GetUserByUUID_Call) Return(_a0 user.User, _a1 error) *MockUserSrvcClient_GetUserByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserSrvcClient_GetUserByUUID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (user.User, error)) *MockUserSrvcClient_GetUserByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUsername provides a mock function with given fields: ctx, username
func (_m *MockUserSrvcClient) GetUserByUsername(ctx context.Context, username string) (user.User, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (user.User, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) user.User); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(user.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserSrvcClient_GetUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsername'
type MockUserSrvcClient_GetUserByUsername_Call struct {
	*mock.Call
}

// GetUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserSrvcClient_Expecter) GetUserByUsername(ctx interface{}, username interface{}) *MockUserSrvcClient_GetUserByUsername_Call {
	return &MockUserSrvcClient_GetUserByUsername_Call{Call: _e.mock.On("GetUserByUsername", ctx, username)}
}

func (_c *MockUserSrvcClient_GetUserByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUserSrvcClient_GetUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserSrvcClient_GetUserByUsername_Call) Return(_a0 user.User, _a1 error) *MockUserSrvcClient_GetUserByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserSrvcClient_GetUserByUsername_Call) RunAndReturn(run func(context.Context, string) (user.User, error)) *MockUserSrvcClient_GetUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsernames provides a mock function with given fields: ctx, uuids
func (_m *MockUserSrvcClient) GetUsernames(ctx context.Context, uuids []uuid.UUID) ([]string, error) {
	ret := _m.Called(ctx, uuids)

	if len(ret) == 0 {
		panic("no return value specified for GetUsernames")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]string, error)); ok {
		return rf(ctx, uuids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []string); ok {
		r0 = rf(ctx, uuids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, uuids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserSrvcClient_GetUsernames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsernames'
type MockUserSrvcClient_GetUsernames_Call struct {
	*mock.Call
}

// GetUsernames is a helper method to define mock.On call
//   - ctx context.Context
//   - uuids []uuid.UUID
func (_e *MockUserSrvcClient_Expecter) GetUsernames(ctx interface{}, uuids interface{}) *MockUserSrvcClient_GetUsernames_Call {
	return &MockUserSrvcClient_GetUsernames_Call{Call: _e.mock.On("GetUsernames", ctx, uuids)}
}

func (_c *MockUserSrvcClient_GetUsernames_Call) Run(run func(ctx context.Context, uuids []uuid.UUID)) *MockUserSrvcClient_GetUsernames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *MockUserSrvcClient_GetUsernames_Call) Return(_a0 []string, _a1 error) *MockUserSrvcClient_GetUsernames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserSrvcClient_GetUsernames_Call) RunAndReturn(run func(context.Context, []uuid.UUID) ([]string, error)) *MockUserSrvcClient_GetUsernames_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, username, password
func (_m *MockUserSrvcClient) Login(ctx context.Context, username string, password string) (*user.User, error) {
	ret := _m.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*user.User, error)); ok {
		return rf(ctx, username, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *user.User); ok {
		r0 = rf(ctx, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserSrvcClient_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockUserSrvcClient_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockUserSrvcClient_Expecter) Login(ctx interface{}, username interface{}, password interface{}) *MockUserSrvcClient_Login_Call {
	return &MockUserSrvcClient_Login_Call{Call: _e.mock.On("Login", ctx, username, password)}
}

func (_c *MockUserSrvcClient_Login_Call) Run(run func(ctx context.Context, username string, password string)) *MockUserSrvcClient_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserSrvcClient_Login_Call) Return(_a0 *user.User, _a1 error) *MockUserSrvcClient_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserSrvcClient_Login_Call) RunAndReturn(run func(context.Context, string, string) (*user.User, error)) *MockUserSrvcClient_Login_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserSrvcClient creates a new instance of MockUserSrvcClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserSrvcClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserSrvcClient {
	mock := &MockUserSrvcClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
