with-expecter: true
issue-845-fix: True
packages:
  github.com/programme-lv/backend/common/s3bucket:
    config:
      all: true
      filename: "mock_{{.InterfaceName}}.go"
      dir: "mocks/s3bucket"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "{{.PackageName}}"
  github.com/programme-lv/backend/user:
    config:
      all: true
      filename: "mock_{{.InterfaceName}}.go"
      dir: "mocks/mockuser"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "mockuser"
  github.com/programme-lv/backend/task/srvc:
    config:
      all: true
      filename: "mock_{{.InterfaceName}}.go"
      dir: "mocks/mocktasksrvc"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "mocktasksrvc"
  github.com/programme-lv/backend/subm/submsrvc/submadapter:
    config:
      all: true
      filename: "mock_{{.InterfaceName}}.go"
      dir: "mocks/submadapter"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "{{.PackageName}}"