with-expecter: true
issue-845-fix: True
packages:
  github.com/programme-lv/backend/subm/submsrvc/submadapter:
    config:
      all: true
      filename: "mock_{{.InterfaceName}}.go"
      dir: "mocks/submadapter"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "{{.PackageName}}"