with-expecter: true
issue-845-fix: True
resolve-type-alias: False
disable-version-string: True
packages:
  github.com/programme-lv/backend/modules/task/srvc:
    interfaces:
      TaskPgRepo:
        config:
          filename: "mock_{{.InterfaceName}}.go"
          dir: "gen/mocks/mocktasksrvc"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: "mocktasksrvc"
          template: "testify"
