services:
  postgres:
    image: postgres:17
    container_name: local-proglv-pg
    environment:
      POSTGRES_USER: proglv
      POSTGRES_PASSWORD: proglv
      POSTGRES_DB: proglv
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
