// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocktasksrvc

import (
	context "context"

	srvc "github.com/programme-lv/backend/task/srvc"
	mock "github.com/stretchr/testify/mock"
)

// MockTaskSrvcClient is an autogenerated mock type for the TaskSrvcClient type
type MockTaskSrvcClient struct {
	mock.Mock
}

type MockTaskSrvcClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskSrvcClient) EXPECT() *MockTaskSrvcClient_Expecter {
	return &MockTaskSrvcClient_Expecter{mock: &_m.Mock}
}

// CreateTask provides a mock function with given fields: ctx, task
func (_m *MockTaskSrvcClient) CreateTask(ctx context.Context, task srvc.Task) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, srvc.Task) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskSrvcClient_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockTaskSrvcClient_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task srvc.Task
func (_e *MockTaskSrvcClient_Expecter) CreateTask(ctx interface{}, task interface{}) *MockTaskSrvcClient_CreateTask_Call {
	return &MockTaskSrvcClient_CreateTask_Call{Call: _e.mock.On("CreateTask", ctx, task)}
}

func (_c *MockTaskSrvcClient_CreateTask_Call) Run(run func(ctx context.Context, task srvc.Task)) *MockTaskSrvcClient_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(srvc.Task))
	})
	return _c
}

func (_c *MockTaskSrvcClient_CreateTask_Call) Return(_a0 error) *MockTaskSrvcClient_CreateTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskSrvcClient_CreateTask_Call) RunAndReturn(run func(context.Context, srvc.Task) error) *MockTaskSrvcClient_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteIllustrationImg provides a mock function with given fields: ctx, taskId
func (_m *MockTaskSrvcClient) DeleteIllustrationImg(ctx context.Context, taskId string) error {
	ret := _m.Called(ctx, taskId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIllustrationImg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, taskId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskSrvcClient_DeleteIllustrationImg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIllustrationImg'
type MockTaskSrvcClient_DeleteIllustrationImg_Call struct {
	*mock.Call
}

// DeleteIllustrationImg is a helper method to define mock.On call
//   - ctx context.Context
//   - taskId string
func (_e *MockTaskSrvcClient_Expecter) DeleteIllustrationImg(ctx interface{}, taskId interface{}) *MockTaskSrvcClient_DeleteIllustrationImg_Call {
	return &MockTaskSrvcClient_DeleteIllustrationImg_Call{Call: _e.mock.On("DeleteIllustrationImg", ctx, taskId)}
}

func (_c *MockTaskSrvcClient_DeleteIllustrationImg_Call) Run(run func(ctx context.Context, taskId string)) *MockTaskSrvcClient_DeleteIllustrationImg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskSrvcClient_DeleteIllustrationImg_Call) Return(_a0 error) *MockTaskSrvcClient_DeleteIllustrationImg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskSrvcClient_DeleteIllustrationImg_Call) RunAndReturn(run func(context.Context, string) error) *MockTaskSrvcClient_DeleteIllustrationImg_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteStatementImage provides a mock function with given fields: ctx, taskId, filename
func (_m *MockTaskSrvcClient) DeleteStatementImage(ctx context.Context, taskId string, filename string) error {
	ret := _m.Called(ctx, taskId, filename)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStatementImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, taskId, filename)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskSrvcClient_DeleteStatementImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStatementImage'
type MockTaskSrvcClient_DeleteStatementImage_Call struct {
	*mock.Call
}

// DeleteStatementImage is a helper method to define mock.On call
//   - ctx context.Context
//   - taskId string
//   - filename string
func (_e *MockTaskSrvcClient_Expecter) DeleteStatementImage(ctx interface{}, taskId interface{}, filename interface{}) *MockTaskSrvcClient_DeleteStatementImage_Call {
	return &MockTaskSrvcClient_DeleteStatementImage_Call{Call: _e.mock.On("DeleteStatementImage", ctx, taskId, filename)}
}

func (_c *MockTaskSrvcClient_DeleteStatementImage_Call) Run(run func(ctx context.Context, taskId string, filename string)) *MockTaskSrvcClient_DeleteStatementImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTaskSrvcClient_DeleteStatementImage_Call) Return(_a0 error) *MockTaskSrvcClient_DeleteStatementImage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskSrvcClient_DeleteStatementImage_Call) RunAndReturn(run func(context.Context, string, string) error) *MockTaskSrvcClient_DeleteStatementImage_Call {
	_c.Call.Return(run)
	return _c
}

// ExportTaskAsZip provides a mock function with given fields: ctx, taskId
func (_m *MockTaskSrvcClient) ExportTaskAsZip(ctx context.Context, taskId string) ([]byte, error) {
	ret := _m.Called(ctx, taskId)

	if len(ret) == 0 {
		panic("no return value specified for ExportTaskAsZip")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, taskId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, taskId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, taskId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskSrvcClient_ExportTaskAsZip_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportTaskAsZip'
type MockTaskSrvcClient_ExportTaskAsZip_Call struct {
	*mock.Call
}

// ExportTaskAsZip is a helper method to define mock.On call
//   - ctx context.Context
//   - taskId string
func (_e *MockTaskSrvcClient_Expecter) ExportTaskAsZip(ctx interface{}, taskId interface{}) *MockTaskSrvcClient_ExportTaskAsZip_Call {
	return &MockTaskSrvcClient_ExportTaskAsZip_Call{Call: _e.mock.On("ExportTaskAsZip", ctx, taskId)}
}

func (_c *MockTaskSrvcClient_ExportTaskAsZip_Call) Run(run func(ctx context.Context, taskId string)) *MockTaskSrvcClient_ExportTaskAsZip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskSrvcClient_ExportTaskAsZip_Call) Return(_a0 []byte, _a1 error) *MockTaskSrvcClient_ExportTaskAsZip_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskSrvcClient_ExportTaskAsZip_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *MockTaskSrvcClient_ExportTaskAsZip_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublicUrlForIllustrImg provides a mock function with given fields: ctx, illstrImgS3Key
func (_m *MockTaskSrvcClient) GetPublicUrlForIllustrImg(ctx context.Context, illstrImgS3Key string) (string, error) {
	ret := _m.Called(ctx, illstrImgS3Key)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicUrlForIllustrImg")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, illstrImgS3Key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, illstrImgS3Key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, illstrImgS3Key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskSrvcClient_GetPublicUrlForIllustrImg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublicUrlForIllustrImg'
type MockTaskSrvcClient_GetPublicUrlForIllustrImg_Call struct {
	*mock.Call
}

// GetPublicUrlForIllustrImg is a helper method to define mock.On call
//   - ctx context.Context
//   - illstrImgS3Key string
func (_e *MockTaskSrvcClient_Expecter) GetPublicUrlForIllustrImg(ctx interface{}, illstrImgS3Key interface{}) *MockTaskSrvcClient_GetPublicUrlForIllustrImg_Call {
	return &MockTaskSrvcClient_GetPublicUrlForIllustrImg_Call{Call: _e.mock.On("GetPublicUrlForIllustrImg", ctx, illstrImgS3Key)}
}

func (_c *MockTaskSrvcClient_GetPublicUrlForIllustrImg_Call) Run(run func(ctx context.Context, illstrImgS3Key string)) *MockTaskSrvcClient_GetPublicUrlForIllustrImg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskSrvcClient_GetPublicUrlForIllustrImg_Call) Return(_a0 string, _a1 error) *MockTaskSrvcClient_GetPublicUrlForIllustrImg_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskSrvcClient_GetPublicUrlForIllustrImg_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockTaskSrvcClient_GetPublicUrlForIllustrImg_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublicUrlForStatementImage provides a mock function with given fields: ctx, statementImageS3Key
func (_m *MockTaskSrvcClient) GetPublicUrlForStatementImage(ctx context.Context, statementImageS3Key string) (string, error) {
	ret := _m.Called(ctx, statementImageS3Key)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicUrlForStatementImage")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, statementImageS3Key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, statementImageS3Key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, statementImageS3Key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskSrvcClient_GetPublicUrlForStatementImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublicUrlForStatementImage'
type MockTaskSrvcClient_GetPublicUrlForStatementImage_Call struct {
	*mock.Call
}

// GetPublicUrlForStatementImage is a helper method to define mock.On call
//   - ctx context.Context
//   - statementImageS3Key string
func (_e *MockTaskSrvcClient_Expecter) GetPublicUrlForStatementImage(ctx interface{}, statementImageS3Key interface{}) *MockTaskSrvcClient_GetPublicUrlForStatementImage_Call {
	return &MockTaskSrvcClient_GetPublicUrlForStatementImage_Call{Call: _e.mock.On("GetPublicUrlForStatementImage", ctx, statementImageS3Key)}
}

func (_c *MockTaskSrvcClient_GetPublicUrlForStatementImage_Call) Run(run func(ctx context.Context, statementImageS3Key string)) *MockTaskSrvcClient_GetPublicUrlForStatementImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskSrvcClient_GetPublicUrlForStatementImage_Call) Return(_a0 string, _a1 error) *MockTaskSrvcClient_GetPublicUrlForStatementImage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskSrvcClient_GetPublicUrlForStatementImage_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockTaskSrvcClient_GetPublicUrlForStatementImage_Call {
	_c.Call.Return(run)
	return _c
}

// GetTask provides a mock function with given fields: ctx, shortId
func (_m *MockTaskSrvcClient) GetTask(ctx context.Context, shortId string) (srvc.Task, error) {
	ret := _m.Called(ctx, shortId)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 srvc.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (srvc.Task, error)); ok {
		return rf(ctx, shortId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) srvc.Task); ok {
		r0 = rf(ctx, shortId)
	} else {
		r0 = ret.Get(0).(srvc.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskSrvcClient_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type MockTaskSrvcClient_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - ctx context.Context
//   - shortId string
func (_e *MockTaskSrvcClient_Expecter) GetTask(ctx interface{}, shortId interface{}) *MockTaskSrvcClient_GetTask_Call {
	return &MockTaskSrvcClient_GetTask_Call{Call: _e.mock.On("GetTask", ctx, shortId)}
}

func (_c *MockTaskSrvcClient_GetTask_Call) Run(run func(ctx context.Context, shortId string)) *MockTaskSrvcClient_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskSrvcClient_GetTask_Call) Return(_a0 srvc.Task, _a1 error) *MockTaskSrvcClient_GetTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskSrvcClient_GetTask_Call) RunAndReturn(run func(context.Context, string) (srvc.Task, error)) *MockTaskSrvcClient_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskFullNames provides a mock function with given fields: ctx, shortIds
func (_m *MockTaskSrvcClient) GetTaskFullNames(ctx context.Context, shortIds []string) ([]string, error) {
	ret := _m.Called(ctx, shortIds)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskFullNames")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]string, error)); ok {
		return rf(ctx, shortIds)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []string); ok {
		r0 = rf(ctx, shortIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, shortIds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskSrvcClient_GetTaskFullNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskFullNames'
type MockTaskSrvcClient_GetTaskFullNames_Call struct {
	*mock.Call
}

// GetTaskFullNames is a helper method to define mock.On call
//   - ctx context.Context
//   - shortIds []string
func (_e *MockTaskSrvcClient_Expecter) GetTaskFullNames(ctx interface{}, shortIds interface{}) *MockTaskSrvcClient_GetTaskFullNames_Call {
	return &MockTaskSrvcClient_GetTaskFullNames_Call{Call: _e.mock.On("GetTaskFullNames", ctx, shortIds)}
}

func (_c *MockTaskSrvcClient_GetTaskFullNames_Call) Run(run func(ctx context.Context, shortIds []string)) *MockTaskSrvcClient_GetTaskFullNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockTaskSrvcClient_GetTaskFullNames_Call) Return(_a0 []string, _a1 error) *MockTaskSrvcClient_GetTaskFullNames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskSrvcClient_GetTaskFullNames_Call) RunAndReturn(run func(context.Context, []string) ([]string, error)) *MockTaskSrvcClient_GetTaskFullNames_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskPreview provides a mock function with given fields: ctx, shortId
func (_m *MockTaskSrvcClient) GetTaskPreview(ctx context.Context, shortId string) (srvc.TaskPreview, error) {
	ret := _m.Called(ctx, shortId)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskPreview")
	}

	var r0 srvc.TaskPreview
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (srvc.TaskPreview, error)); ok {
		return rf(ctx, shortId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) srvc.TaskPreview); ok {
		r0 = rf(ctx, shortId)
	} else {
		r0 = ret.Get(0).(srvc.TaskPreview)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskSrvcClient_GetTaskPreview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskPreview'
type MockTaskSrvcClient_GetTaskPreview_Call struct {
	*mock.Call
}

// GetTaskPreview is a helper method to define mock.On call
//   - ctx context.Context
//   - shortId string
func (_e *MockTaskSrvcClient_Expecter) GetTaskPreview(ctx interface{}, shortId interface{}) *MockTaskSrvcClient_GetTaskPreview_Call {
	return &MockTaskSrvcClient_GetTaskPreview_Call{Call: _e.mock.On("GetTaskPreview", ctx, shortId)}
}

func (_c *MockTaskSrvcClient_GetTaskPreview_Call) Run(run func(ctx context.Context, shortId string)) *MockTaskSrvcClient_GetTaskPreview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskSrvcClient_GetTaskPreview_Call) Return(_a0 srvc.TaskPreview, _a1 error) *MockTaskSrvcClient_GetTaskPreview_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskSrvcClient_GetTaskPreview_Call) RunAndReturn(run func(context.Context, string) (srvc.TaskPreview, error)) *MockTaskSrvcClient_GetTaskPreview_Call {
	_c.Call.Return(run)
	return _c
}

// GetTestDownlUrl provides a mock function with given fields: ctx, testFileSha256
func (_m *MockTaskSrvcClient) GetTestDownlUrl(ctx context.Context, testFileSha256 string) (string, error) {
	ret := _m.Called(ctx, testFileSha256)

	if len(ret) == 0 {
		panic("no return value specified for GetTestDownlUrl")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, testFileSha256)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, testFileSha256)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, testFileSha256)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskSrvcClient_GetTestDownlUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTestDownlUrl'
type MockTaskSrvcClient_GetTestDownlUrl_Call struct {
	*mock.Call
}

// GetTestDownlUrl is a helper method to define mock.On call
//   - ctx context.Context
//   - testFileSha256 string
func (_e *MockTaskSrvcClient_Expecter) GetTestDownlUrl(ctx interface{}, testFileSha256 interface{}) *MockTaskSrvcClient_GetTestDownlUrl_Call {
	return &MockTaskSrvcClient_GetTestDownlUrl_Call{Call: _e.mock.On("GetTestDownlUrl", ctx, testFileSha256)}
}

func (_c *MockTaskSrvcClient_GetTestDownlUrl_Call) Run(run func(ctx context.Context, testFileSha256 string)) *MockTaskSrvcClient_GetTestDownlUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskSrvcClient_GetTestDownlUrl_Call) Return(_a0 string, _a1 error) *MockTaskSrvcClient_GetTestDownlUrl_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskSrvcClient_GetTestDownlUrl_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockTaskSrvcClient_GetTestDownlUrl_Call {
	_c.Call.Return(run)
	return _c
}

// ListTaskPreviews provides a mock function with given fields: ctx
func (_m *MockTaskSrvcClient) ListTaskPreviews(ctx context.Context) ([]srvc.TaskPreview, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTaskPreviews")
	}

	var r0 []srvc.TaskPreview
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]srvc.TaskPreview, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []srvc.TaskPreview); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]srvc.TaskPreview)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskSrvcClient_ListTaskPreviews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTaskPreviews'
type MockTaskSrvcClient_ListTaskPreviews_Call struct {
	*mock.Call
}

// ListTaskPreviews is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaskSrvcClient_Expecter) ListTaskPreviews(ctx interface{}) *MockTaskSrvcClient_ListTaskPreviews_Call {
	return &MockTaskSrvcClient_ListTaskPreviews_Call{Call: _e.mock.On("ListTaskPreviews", ctx)}
}

func (_c *MockTaskSrvcClient_ListTaskPreviews_Call) Run(run func(ctx context.Context)) *MockTaskSrvcClient_ListTaskPreviews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTaskSrvcClient_ListTaskPreviews_Call) Return(_a0 []srvc.TaskPreview, _a1 error) *MockTaskSrvcClient_ListTaskPreviews_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskSrvcClient_ListTaskPreviews_Call) RunAndReturn(run func(context.Context) ([]srvc.TaskPreview, error)) *MockTaskSrvcClient_ListTaskPreviews_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasks provides a mock function with given fields: ctx
func (_m *MockTaskSrvcClient) ListTasks(ctx context.Context) ([]srvc.Task, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 []srvc.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]srvc.Task, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []srvc.Task); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]srvc.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskSrvcClient_ListTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasks'
type MockTaskSrvcClient_ListTasks_Call struct {
	*mock.Call
}

// ListTasks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaskSrvcClient_Expecter) ListTasks(ctx interface{}) *MockTaskSrvcClient_ListTasks_Call {
	return &MockTaskSrvcClient_ListTasks_Call{Call: _e.mock.On("ListTasks", ctx)}
}

func (_c *MockTaskSrvcClient_ListTasks_Call) Run(run func(ctx context.Context)) *MockTaskSrvcClient_ListTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTaskSrvcClient_ListTasks_Call) Return(_a0 []srvc.Task, _a1 error) *MockTaskSrvcClient_ListTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskSrvcClient_ListTasks_Call) RunAndReturn(run func(context.Context) ([]srvc.Task, error)) *MockTaskSrvcClient_ListTasks_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveNames provides a mock function with given fields: ctx, shortIds
func (_m *MockTaskSrvcClient) ResolveNames(ctx context.Context, shortIds []string) ([]string, error) {
	ret := _m.Called(ctx, shortIds)

	if len(ret) == 0 {
		panic("no return value specified for ResolveNames")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]string, error)); ok {
		return rf(ctx, shortIds)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []string); ok {
		r0 = rf(ctx, shortIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, shortIds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskSrvcClient_ResolveNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveNames'
type MockTaskSrvcClient_ResolveNames_Call struct {
	*mock.Call
}

// ResolveNames is a helper method to define mock.On call
//   - ctx context.Context
//   - shortIds []string
func (_e *MockTaskSrvcClient_Expecter) ResolveNames(ctx interface{}, shortIds interface{}) *MockTaskSrvcClient_ResolveNames_Call {
	return &MockTaskSrvcClient_ResolveNames_Call{Call: _e.mock.On("ResolveNames", ctx, shortIds)}
}

func (_c *MockTaskSrvcClient_ResolveNames_Call) Run(run func(ctx context.Context, shortIds []string)) *MockTaskSrvcClient_ResolveNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockTaskSrvcClient_ResolveNames_Call) Return(_a0 []string, _a1 error) *MockTaskSrvcClient_ResolveNames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskSrvcClient_ResolveNames_Call) RunAndReturn(run func(context.Context, []string) ([]string, error)) *MockTaskSrvcClient_ResolveNames_Call {
	_c.Call.Return(run)
	return _c
}

// SearchTasksByName provides a mock function with given fields: ctx, name
func (_m *MockTaskSrvcClient) SearchTasksByName(ctx context.Context, name string) ([]string, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for SearchTasksByName")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskSrvcClient_SearchTasksByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchTasksByName'
type MockTaskSrvcClient_SearchTasksByName_Call struct {
	*mock.Call
}

// SearchTasksByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTaskSrvcClient_Expecter) SearchTasksByName(ctx interface{}, name interface{}) *MockTaskSrvcClient_SearchTasksByName_Call {
	return &MockTaskSrvcClient_SearchTasksByName_Call{Call: _e.mock.On("SearchTasksByName", ctx, name)}
}

func (_c *MockTaskSrvcClient_SearchTasksByName_Call) Run(run func(ctx context.Context, name string)) *MockTaskSrvcClient_SearchTasksByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskSrvcClient_SearchTasksByName_Call) Return(_a0 []string, _a1 error) *MockTaskSrvcClient_SearchTasksByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskSrvcClient_SearchTasksByName_Call) RunAndReturn(run func(context.Context, string) ([]string, error)) *MockTaskSrvcClient_SearchTasksByName_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIllustrationImg provides a mock function with given fields: ctx, taskId, img
func (_m *MockTaskSrvcClient) UpdateIllustrationImg(ctx context.Context, taskId string, img srvc.IllustrationImage) error {
	ret := _m.Called(ctx, taskId, img)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIllustrationImg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, srvc.IllustrationImage) error); ok {
		r0 = rf(ctx, taskId, img)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskSrvcClient_UpdateIllustrationImg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIllustrationImg'
type MockTaskSrvcClient_UpdateIllustrationImg_Call struct {
	*mock.Call
}

// UpdateIllustrationImg is a helper method to define mock.On call
//   - ctx context.Context
//   - taskId string
//   - img srvc.IllustrationImage
func (_e *MockTaskSrvcClient_Expecter) UpdateIllustrationImg(ctx interface{}, taskId interface{}, img interface{}) *MockTaskSrvcClient_UpdateIllustrationImg_Call {
	return &MockTaskSrvcClient_UpdateIllustrationImg_Call{Call: _e.mock.On("UpdateIllustrationImg", ctx, taskId, img)}
}

func (_c *MockTaskSrvcClient_UpdateIllustrationImg_Call) Run(run func(ctx context.Context, taskId string, img srvc.IllustrationImage)) *MockTaskSrvcClient_UpdateIllustrationImg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(srvc.IllustrationImage))
	})
	return _c
}

func (_c *MockTaskSrvcClient_UpdateIllustrationImg_Call) Return(_a0 error) *MockTaskSrvcClient_UpdateIllustrationImg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskSrvcClient_UpdateIllustrationImg_Call) RunAndReturn(run func(context.Context, string, srvc.IllustrationImage) error) *MockTaskSrvcClient_UpdateIllustrationImg_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatementMd provides a mock function with given fields: ctx, taskId, statement
func (_m *MockTaskSrvcClient) UpdateStatementMd(ctx context.Context, taskId string, statement srvc.MarkdownStatement) error {
	ret := _m.Called(ctx, taskId, statement)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatementMd")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, srvc.MarkdownStatement) error); ok {
		r0 = rf(ctx, taskId, statement)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskSrvcClient_UpdateStatementMd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatementMd'
type MockTaskSrvcClient_UpdateStatementMd_Call struct {
	*mock.Call
}

// UpdateStatementMd is a helper method to define mock.On call
//   - ctx context.Context
//   - taskId string
//   - statement srvc.MarkdownStatement
func (_e *MockTaskSrvcClient_Expecter) UpdateStatementMd(ctx interface{}, taskId interface{}, statement interface{}) *MockTaskSrvcClient_UpdateStatementMd_Call {
	return &MockTaskSrvcClient_UpdateStatementMd_Call{Call: _e.mock.On("UpdateStatementMd", ctx, taskId, statement)}
}

func (_c *MockTaskSrvcClient_UpdateStatementMd_Call) Run(run func(ctx context.Context, taskId string, statement srvc.MarkdownStatement)) *MockTaskSrvcClient_UpdateStatementMd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(srvc.MarkdownStatement))
	})
	return _c
}

func (_c *MockTaskSrvcClient_UpdateStatementMd_Call) Return(_a0 error) *MockTaskSrvcClient_UpdateStatementMd_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskSrvcClient_UpdateStatementMd_Call) RunAndReturn(run func(context.Context, string, srvc.MarkdownStatement) error) *MockTaskSrvcClient_UpdateStatementMd_Call {
	_c.Call.Return(run)
	return _c
}

// UploadIllustrationImg provides a mock function with given fields: ctx, mimeType, body
func (_m *MockTaskSrvcClient) UploadIllustrationImg(ctx context.Context, mimeType string, body []byte) (string, error) {
	ret := _m.Called(ctx, mimeType, body)

	if len(ret) == 0 {
		panic("no return value specified for UploadIllustrationImg")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) (string, error)); ok {
		return rf(ctx, mimeType, body)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) string); ok {
		r0 = rf(ctx, mimeType, body)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, mimeType, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskSrvcClient_UploadIllustrationImg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadIllustrationImg'
type MockTaskSrvcClient_UploadIllustrationImg_Call struct {
	*mock.Call
}

// UploadIllustrationImg is a helper method to define mock.On call
//   - ctx context.Context
//   - mimeType string
//   - body []byte
func (_e *MockTaskSrvcClient_Expecter) UploadIllustrationImg(ctx interface{}, mimeType interface{}, body interface{}) *MockTaskSrvcClient_UploadIllustrationImg_Call {
	return &MockTaskSrvcClient_UploadIllustrationImg_Call{Call: _e.mock.On("UploadIllustrationImg", ctx, mimeType, body)}
}

func (_c *MockTaskSrvcClient_UploadIllustrationImg_Call) Run(run func(ctx context.Context, mimeType string, body []byte)) *MockTaskSrvcClient_UploadIllustrationImg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockTaskSrvcClient_UploadIllustrationImg_Call) Return(_a0 string, _a1 error) *MockTaskSrvcClient_UploadIllustrationImg_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskSrvcClient_UploadIllustrationImg_Call) RunAndReturn(run func(context.Context, string, []byte) (string, error)) *MockTaskSrvcClient_UploadIllustrationImg_Call {
	_c.Call.Return(run)
	return _c
}

// UploadStatementImage provides a mock function with given fields: ctx, taskId, filename, mimeType, body
func (_m *MockTaskSrvcClient) UploadStatementImage(ctx context.Context, taskId string, filename string, mimeType string, body []byte) (string, error) {
	ret := _m.Called(ctx, taskId, filename, mimeType, body)

	if len(ret) == 0 {
		panic("no return value specified for UploadStatementImage")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []byte) (string, error)); ok {
		return rf(ctx, taskId, filename, mimeType, body)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []byte) string); ok {
		r0 = rf(ctx, taskId, filename, mimeType, body)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, []byte) error); ok {
		r1 = rf(ctx, taskId, filename, mimeType, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskSrvcClient_UploadStatementImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadStatementImage'
type MockTaskSrvcClient_UploadStatementImage_Call struct {
	*mock.Call
}

// UploadStatementImage is a helper method to define mock.On call
//   - ctx context.Context
//   - taskId string
//   - filename string
//   - mimeType string
//   - body []byte
func (_e *MockTaskSrvcClient_Expecter) UploadStatementImage(ctx interface{}, taskId interface{}, filename interface{}, mimeType interface{}, body interface{}) *MockTaskSrvcClient_UploadStatementImage_Call {
	return &MockTaskSrvcClient_UploadStatementImage_Call{Call: _e.mock.On("UploadStatementImage", ctx, taskId, filename, mimeType, body)}
}

func (_c *MockTaskSrvcClient_UploadStatementImage_Call) Run(run func(ctx context.Context, taskId string, filename string, mimeType string, body []byte)) *MockTaskSrvcClient_UploadStatementImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].([]byte))
	})
	return _c
}

func (_c *MockTaskSrvcClient_UploadStatementImage_Call) Return(_a0 string, _a1 error) *MockTaskSrvcClient_UploadStatementImage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskSrvcClient_UploadStatementImage_Call) RunAndReturn(run func(context.Context, string, string, string, []byte) (string, error)) *MockTaskSrvcClient_UploadStatementImage_Call {
	_c.Call.Return(run)
	return _c
}

// UploadStatementPdf provides a mock function with given fields: ctx, body
func (_m *MockTaskSrvcClient) UploadStatementPdf(ctx context.Context, body []byte) (string, error) {
	ret := _m.Called(ctx, body)

	if len(ret) == 0 {
		panic("no return value specified for UploadStatementPdf")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) (string, error)); ok {
		return rf(ctx, body)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte) string); ok {
		r0 = rf(ctx, body)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskSrvcClient_UploadStatementPdf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadStatementPdf'
type MockTaskSrvcClient_UploadStatementPdf_Call struct {
	*mock.Call
}

// UploadStatementPdf is a helper method to define mock.On call
//   - ctx context.Context
//   - body []byte
func (_e *MockTaskSrvcClient_Expecter) UploadStatementPdf(ctx interface{}, body interface{}) *MockTaskSrvcClient_UploadStatementPdf_Call {
	return &MockTaskSrvcClient_UploadStatementPdf_Call{Call: _e.mock.On("UploadStatementPdf", ctx, body)}
}

func (_c *MockTaskSrvcClient_UploadStatementPdf_Call) Run(run func(ctx context.Context, body []byte)) *MockTaskSrvcClient_UploadStatementPdf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *MockTaskSrvcClient_UploadStatementPdf_Call) Return(_a0 string, _a1 error) *MockTaskSrvcClient_UploadStatementPdf_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskSrvcClient_UploadStatementPdf_Call) RunAndReturn(run func(context.Context, []byte) (string, error)) *MockTaskSrvcClient_UploadStatementPdf_Call {
	_c.Call.Return(run)
	return _c
}

// UploadTestFile provides a mock function with given fields: ctx, body
func (_m *MockTaskSrvcClient) UploadTestFile(ctx context.Context, body []byte) error {
	ret := _m.Called(ctx, body)

	if len(ret) == 0 {
		panic("no return value specified for UploadTestFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = rf(ctx, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskSrvcClient_UploadTestFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadTestFile'
type MockTaskSrvcClient_UploadTestFile_Call struct {
	*mock.Call
}

// UploadTestFile is a helper method to define mock.On call
//   - ctx context.Context
//   - body []byte
func (_e *MockTaskSrvcClient_Expecter) UploadTestFile(ctx interface{}, body interface{}) *MockTaskSrvcClient_UploadTestFile_Call {
	return &MockTaskSrvcClient_UploadTestFile_Call{Call: _e.mock.On("UploadTestFile", ctx, body)}
}

func (_c *MockTaskSrvcClient_UploadTestFile_Call) Run(run func(ctx context.Context, body []byte)) *MockTaskSrvcClient_UploadTestFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *MockTaskSrvcClient_UploadTestFile_Call) Return(_a0 error) *MockTaskSrvcClient_UploadTestFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskSrvcClient_UploadTestFile_Call) RunAndReturn(run func(context.Context, []byte) error) *MockTaskSrvcClient_UploadTestFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskSrvcClient creates a new instance of MockTaskSrvcClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskSrvcClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskSrvcClient {
	mock := &MockTaskSrvcClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
