services:
  postgres:
    image: postgres:17
    container_name: local-proglv-pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: proglv
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
