# @addr=https://0f6de9e9w5.execute-api.eu-central-1.amazonaws.com
@addr=http://localhost:8080
# @addr=https://api.programme.lv
@uuid=1f5b8a10-67c2-4374-a378-0bc2a07bc682
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkVsaWFhM2FiYSIsImZpcnN0bmFtZSI6IkpvaG4iLCJsYXN0bmFtZSI6IkRvZSIsImVtYWlsIjoiam9obmRvZWEzYWFAZXhhbXBsZS5jb20iLCJ1dWlkIjoiNGZmYzc4ZjUtMDliNi00MGYwLWE2MzEtMTc4ZjgyNjgxYmI2IiwiZXhwIjoxNzIyOTgwNDIyfQ.-MwbRPeJmg9qqDlVWp4SxvQGrjRoiINN71tE4gR4pdM
### Create User
POST {{addr}}/users
Content-Type: application/json

{
  "username": "asdafasdfaasdfasdf",
  "email": "johnadoeaa3aaaa@example.com",
  "password": "pasaaaaaaaaaa",
  "firstname": "John",
  "lastname": "Doe"
}

### Login
POST {{addr}}/auth/login
Content-Type: application/json

{
  "username": "Eliaa3aba",
  "password": "pas"
}

### Get auth status
GET {{addr}}/auth/current/jwt
Authorization: Bearer {{token}}


### Get task list
GET {{addr}}/tasks

### Get specific task
GET {{addr}}/tasks/kvadrputekl

### Get submission list
GET {{addr}}/submissions

### Get specific submission
GET {{addr}}/submissions/{{uuid}}

### Create submission
POST {{addr}}/submissions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "submission": "print(factorial(5))",
  "username": "coder123",
  "programming_lang_id": "go",
  "task_code_id": "kvadrputekl"
}