# @addr=https://0f6de9e9w5.execute-api.eu-central-1.amazonaws.com
@addr=http://localhost:8080
# @addr=https://api.programme.lv
@uuid=1f5b8a10-67c2-4374-a378-0bc2a07bc682
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFiYyIsImZpcnN0bmFtZSI6IkpvaG4iLCJsYXN0bmFtZSI6IkRvZSIsImVtYWlsIjoiYWJjQGV4YW1wbGUuY29tIiwidXVpZCI6IjBjODFkNGVkLTM0ZDYtNDE1ZS1hYmY5LTVjMTczMTdhNDUzOSIsImV4cCI6MTcyMzMyNDMwMH0.AyzjnFOQ7zqiLC9R9_ZmGobJ19V8jB6a4Mw0dClwlVU
### Create User
POST {{addr}}/users
Content-Type: application/json

{
  "username": "abca",
  "email": "abca@example.com",
  "password": "12345678",
  "firstname": "John",
  "lastname": "Doe"
}

### Login
POST {{addr}}/auth/login
Content-Type: application/json

{
  "username": "abc",
  "password": "12345678"
}

### Get auth status
GET {{addr}}/auth/current/jwt
Authorization: Bearer {{token}}


### Get task list
GET {{addr}}/tasks

### Get specific task
GET {{addr}}/tasks/kvadrputekl

### Get submission list
GET {{addr}}/submissions

### Get specific submission
GET {{addr}}/submissions/{{uuid}}

### Create submission
POST {{addr}}/submissions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "submission": "print(factorial(5))",
  "username": "abca",
  "programming_lang_id": "go",
  "task_code_id": "kvadrputekl"
}