# @addr=https://0f6de9e9w5.execute-api.eu-central-1.amazonaws.com
@addr=http://localhost:8080
@uuid=1f5b8a10-67c2-4374-a378-0bc2a07bc682
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkVsaWFhM2FiYSIsImZpcnN0bmFtZSI6IkpvaG4iLCJsYXN0bmFtZSI6IkRvZSIsImVtYWlsIjoiam9obmRvZWEzYWFAZXhhbXBsZS5jb20iLCJ1dWlkIjoiNGZmYzc4ZjUtMDliNi00MGYwLWE2MzEtMTc4ZjgyNjgxYmI2IiwiZXhwIjoxNzIyNzcyMDA1fQ.GJ7qSJSDmqQorcundI9Rxog-1BdgMMf-2c0JaYFRFdk

### Create User
POST {{addr}}/users
Content-Type: application/json

{
  "username": "Eliaa3aba",
  "email": "johndoea3aa@example.com",
  "password": "password123",
  "firstname": "John",
  "lastname": "Doe"
}

### Get User
GET {{addr}}/users/{{uuid}}

### Update User
PUT h{{addr}}/users/{uuid}
Content-Type: application/json

{
  "username": "johnupdated",
  "email": "johnupdated@example.com"
}

### Delete User
DELETE {{addr}}/users/{uuid}

### List Users
GET {{addr}}/users

### Login
POST {{addr}}/auth/login
Content-Type: application/json

{
  "username": "Eliaa3aba",
  "password": "password123"
}

### Get auth status
GET {{addr}}/auth/current/jwt
Authorization: Bearer {{token}}
